### PR TITLE
Fix for gcloud dns: update dns_provider and dns_provider_config

### LINKED ISSUE #166: Google DNS bug - cloudflare dns_provider used in /dns/gcloud/main.tf
Using magic_castle version `11.0` (AWS) I get the following error when using the google dns module.

```
╷
│ Error: cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN
│ 
│   with module.dns.module.acme.acme_certificate.certificate,
│   on dns/acme/main.tf line 41, in resource "acme_certificate" "certificate":
│   41: resource "acme_certificate" "certificate" {
│ 
╵
```

I guessed the error stemmed from the reference of cloudflare here:

https://github.com/ComputeCanada/magic_castle/blob/aaec453e9883d6a1a3c4a1cb5e7bbba26dc4ddfc/dns/gcloud/main.tf#L32-L42

So, changing it to `google` instead I got the following error:

```
module.dns.module.acme.acme_certificate.certificate: Creating...
╷
│ Error: google: unsupported DNS challenge provider
│ 
│   with module.dns.module.acme.acme_certificate.certificate,
│   on dns/acme/main.tf line 41, in resource "acme_certificate" "certificate":
│   41: resource "acme_certificate" "certificate" {
│ 
╵
```

Googling a bit I found [the `gcloud` DNS challenge provider](https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-gcloud) and tried `gcloud` instead.

```
╷
│ Error: googlecloud: project name missing
│ 
│   with module.dns.module.acme.acme_certificate.certificate,
│   on dns/acme/main.tf line 41, in resource "acme_certificate" "certificate":
│   41: resource "acme_certificate" "certificate" {
│ 
╵
```

I think this can relate to me deploying to AWS and using Google DNS based on [this documentation](https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-gcloud#argument-reference) summarized below:

> `GCE_PROJECT` - Project name (by default, the project name is auto-detected by using the metadata service).

Perhaps it could have been autodetected normally, but isn't as I deploy to AWS? I'm not sure... Anyhow, I assume I need to explicitly point to the _GCP project_ where i have Google DNS management of the domain in question.

Btw note that I have already `gcloud config set project domains-sos` which is the GCP project of relevance, but this wasn't enough.

> The following arguments can be either passed as environment variables, or directly through the config block in the dns_challenge argument in the acme_certificate resource. For more details, see here.

Setting `GCE_PROJECT` would probably do the trick, but I only verified it to work like by tweaking `/dns/acme/main.tf` like this.

```diff
 # /dns/acme/main.tf
 module "acme" {
   source              = "../acme"
   dns_provider        = "gcloud"
+  dns_provider_config = {
+    GCE_PROJECT = var.project
+  }
   name                = lower(var.name)
   domain              = var.domain
   email               = var.email
   sudoer_username     = var.sudoer_username
   public_instances    = var.public_instances
   ssh_private_key     = var.ssh_private_key
   ssl_tags            = var.ssl_tags
 }
```

Below is what my `/main.tf` looked like that sets variables accessed above.

```
# Uncomment to register your domain name with Google Cloud
module "dns" {
  source           = "./dns/gcloud"
  email            = "my@email.se"
  project          = "domains-sos"
  zone_name        = "jupytearth-org"
  name             = module.aws.cluster_name
  domain           = module.aws.domain
  public_instances = module.aws.public_instances
  ssh_private_key  = module.aws.ssh_private_key
  sudoer_username  = module.aws.accounts.sudoer.username
}
```

@cmd-ntrf I'll go ahead and open a PR as I now feel quite confident about these kinds of changes could make sense.

### PR DESCRIPTION
**Pull request by consideRatio**
Closes #166.

I opened this PR as it felt like a viable resolution to #166 and if not a sensible way to discuss resolving the issue more concretely.

### CODE REVIEW

**Comment by cmd-ntrf** [comment]
It is indeed the right resolution. A regression was introduced in 11.0. Your PR is exactly how acme was declared in the gcloud dns module in 10.2:
https://github.com/ComputeCanada/magic_castle/blob/61edf20f1d1aa1d40b9834e5fa40919ec9965726/dns/gcloud/main.tf#L31

I am not sure how this happened, probably a bad copy-paste on my side and the lack of tests for the dns providers is showing here.

**Comment by consideRatio** [comment]
Ah, I see that https://github.com/ComputeCanada/magic_castle/commit/5900133bfd58296ff073a4432ec75e0ecdfdeb19 made the change. There are more changes, are there something that needs to be fixed besides this in that commit that introduced this regression?

**Comment by cmd-ntrf** [comment]
No, all good. You nailed it!
Thank you!

**Comment by consideRatio** [comment]
Wieeee my first PR merged in this repo!!

image

**Pull request merged**
