### PR TITLE
Typo in some READMEs

### PR DESCRIPTION
**Pull request by ocaisa**
(I think)

### CODE REVIEW

**Comment by ocaisa** [comment]
Not sure because the same typo is in 4 places (but not in OpenStack)

**Comment by cmd-ntrf** [comment]
Thanks!

Would you mind fixing it in the 3 other places you found the typo?

**Comment by cmd-ntrf** [comment]
If we ever meet, I owe you a beer.
https://github.com/ComputeCanada/magic_castle/issues/33

**Comment by ocaisa** [comment]
Ha, cool, I will come to collect!

**Pull request merged**
